/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradledefinitivo;
import java.util.HashMap;
import java.util.Map;

public class GestorDeLibros {
    private Map<String, Map<String, Boolean>> gestorDeLibros = new HashMap<>();

    // Añadir un libro
    public Map<String, Map<String, Boolean>> añadirLibro(String autor, String titulo) {
        gestorDeLibros.putIfAbsent(autor, new HashMap<>());
        gestorDeLibros.get(autor).put(titulo, false); // Por defecto, marcamos el libro como no leído
        return gestorDeLibros;
    }

    // Eliminar un libro
    public Map<String, Map<String, Boolean>> eliminarLibro(String autor, String titulo) {
        if (gestorDeLibros.containsKey(autor)) {
            gestorDeLibros.get(autor).remove(titulo);
            // Si no quedan más libros para el autor, eliminamos el autor del mapa principal
            if (gestorDeLibros.get(autor).isEmpty()) {
                gestorDeLibros.remove(autor);
            }
        }
        return gestorDeLibros;
    }

    // Listar los libros
    public void enumLibros() {
        for (Map.Entry<String, Map<String, Boolean>> autorEntry : gestorDeLibros.entrySet()) {
            String autor = autorEntry.getKey();
            Map<String, Boolean> libros = autorEntry.getValue();
            System.out.println("Autor: " + autor);
            for (Map.Entry<String, Boolean> libroEntry : libros.entrySet()) {
                String titulo = libroEntry.getKey();
                boolean leido = libroEntry.getValue();
                System.out.println(" - Título: " + titulo + ", Leído: " + leido);
            }
        }
    }

    // Marcar un libro como leído
    public boolean marcarLeido(String autor, String titulo) {
        if (gestorDeLibros.containsKey(autor)) {
            gestorDeLibros.get(autor).put(titulo, true);
            return true;
        }
        return false;
    }

        public String verLibrosLeidos(String autor){
            Map<String, Boolean> libros = gestorDeLibros.getOrDefault(autor, null);

            libros.forEach((titulo,leido) -> { if(leido){ System.out.println(titulo);}});

            return libros.toString();
        }
}